ProjectFlask/admin/src/web/__init__.py
from flask import Flask  # <-- importamos la clase Flask
from flask import (
    render_template,
)  # <-- importamos la función render_template para renderizar templates
from flask_session import Session  # <-- importamos la clase Session de flask_session
from src.web import error  # <-- importamos el módulo de errores
from src.web.config import config  # <-- importamos la configuración
from src.core import database  # <-- importamos la base de datos
from src.web import routes  # <-- importamos las rutas
from src.web import commands  # <-- importamos los comandos
from src.web.helpers import auth  # <-- importamos el módulo de autenticación
import logging  # <-- importamos el módulo de logging que viene con python para ver los logs

logging.basicConfig()  # <-- inicializamos el logging
logging.getLogger("sqlalchemy.engine").setLevel(
    logging.DEBUG
)  # <-- seteamos el nivel de logging para sqlalchemy
session = Session()  # <-- inicializamos la sesión de flask_session


def create_app(
    env="development",  # <-- definimos el entorno de desarrollo
    static_folder="../../static",  # <-- definimos la carpeta de archivos estáticos
):
    """Crea la aplicación de flask"""
    app = Flask(__name__, static_folder=static_folder)  # <-- crea la aplicación
    app.config.from_object(config[env])  # <-- setea la configuración
    session.init_app(app)  # <-- inicializamos la sesión de flask_session
    database.init_app(app)  # <-- inicializamos la base de datos
    commands.register(app)  # <-- registramos los comandos
    routes.register(app)  # <-- registramos las rutas
    # ---- ejemplo de rutas ----

    app.register_error_handler(
        404, error.not_found_error
    )  # <-- registramos el error 404
    app.register_error_handler(
        401, error.unauthorized_error
    )  # <-- registramos el error 401

    app.jinja_env.globals.update(is_authenticated=auth.is_authenticated)

    def sarasa():
        return "sarasa"

    app.add_url_rule("/sarasa", view_func=sarasa)  # <-- forma antigua de agregar rutas

    return app

ProjectFlask/admin/src/web/controllers/auth.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import redirect
from flask import url_for
from flask import session
from src.core import auth

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")


@auth_blueprint.get("/")
def login():
    return render_template("auth/login.html")


@auth_blueprint.post("/authenticate")
def authenticate():
    params = request.form
    user = auth.check_user(params["email"], params["password"])

    if not user:
        flash("Email o clave incorrecta", "error")
        return redirect(url_for("auth.login"))

    session["user"] = user.email
    flash("Bienvenido", "success")
    return redirect(url_for("home"))


@auth_blueprint.get("/logout")
def logout():
    if session.get("user"):
        del session["user"]
        session.clear()
        flash("La sesión se cerro correctamente", "info")

    else:
        flash("No hay ninguna sesión activa", "info")

    return redirect(url_for("auth.login"))

ProjectFlask/admin/src/web/controllers/home.py
from flask import Blueprint, render_template

home_bp = Blueprint("home", __name__, url_prefix="/")  # <-- creamos el blueprint


@home_bp.get("/")  # <-- forma nueva de agregar rutas
def home():
    return render_template("home.html")  # <-- renderizamos el template home.html

ProjectFlask/admin/src/web/controllers/issues.py
from flask import render_template
from flask import Blueprint
from src.core import board

issue_bp = Blueprint("issues", __name__, url_prefix="/consultas")


@issue_bp.get("/")
def index():
    issues = board.list_issues()
    return render_template("issues/index.html", issues=issues)

ProjectFlask/admin/src/web/controllers/users.py
from flask import Blueprint
from flask import render_template
from src.core import auth
from flask import abort
from src.web.helpers.auth import login_required
from src.web.helpers.auth import has_permission

user_blueprint = Blueprint("users", __name__, url_prefix="/usuarios")


@user_blueprint.get("/")
@login_required
def index():
    if not has_permission(["user_index"]):
        return abort(401)
    users = auth.list_users()
    return render_template("users/index.html", users=users)

ProjectFlask/admin/src/web/helpers/auth.py
from functools import wraps
from flask import session
from flask import abort
from src.core.auth import find_user_by_email
from src.core.auth import list_permissions_by_user_id


def is_authenticated(session):
    return session.get("user") is not None


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not is_authenticated(session):
            return abort(401)
        return f(*args, **kwargs)

    return decorated_function


def has_permission(required_permissions_list):
    has_permission = True
    user = find_user_by_email(session.get("user"))
    user_permissions_list = list_permissions_by_user_id(user.id)
    for permission in required_permissions_list:
        if permission not in user_permissions_list:
            print("has_permission === no esta el permiso %s" % permission)
            has_permission = False
            break
    return has_permission

ProjectFlask/admin/src/web/routes.py
from src.web.controllers.issues import issue_bp
from src.web.controllers.auth import auth_blueprint
from src.web.controllers.users import user_blueprint
from src.web.controllers.home import home_bp


def register(app):
    app.register_blueprint(issue_bp)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(home_bp)

ProjectFlask/admin/src/web/templates/error.html
{% extends "layout.html" %}
{% block title %}Error{% endblock %}
{% block head %}
{{super()}}
{% endblock %}
{% block content %}
<h1>{{ error_name }}</h1>
<p class="zoom-area"><b>Error!</b>{{error_description}}</p>
<div class="link-container">
  <a href="{{ url_for('home') }}" class="more-link"> Ir a la Pagina de inicio</a>
</div>
{% endblock %}

ProjectFlask/admin/src/web/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block head %}
{{super()}}
{% endblock %}
{% block content %}
<h1>Inicio</h1>
<p>Pagina de inicio de la aplicación</p>
<a href="{{ url_for('issues.index') }}" class="link">Consultas</a>
{% if is_authenticated(session) %}
<a href="{{url_for('users.index')}}" class="link">Usuarios</a>
<a href="{{url_for('auth.logout')}}">Cerrar sesión</a>
{% else %}
<a href="{{url_for('auth.login')}}">Iniciar sesión</a>
{% endif %}
{% endblock %}

ProjectFlask/admin/src/web/templates/issues/index.html
{% extends "layout.html" %}
{% block title %}Consultas{% endblock %}
{% block head %} {{super()}} {% endblock %}
{% block content %}
<h1>Consultas</h1>

<table class="index-table box">
  <thead>
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>Titulo</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Etiquetas</th>
    </tr>
  </thead>
  <tbody>
    {% for issue in issues %}
    <tr>
      <td>{{ issue.id }}</td>
      <td>{{ issue.email }}</td>
      <td>{{ issue.title }}</td>
      <td>{{ issue.description }}</td>
      <td>{{ issue.status }}</td>
      <td>
        {% for label in issue.labels %}
        {{ label.title }}
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>
<a href="{{url_for('home')}}">Volver al Inicio</a>
{% endblock %}

ProjectFlask/admin/src/web/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  {% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
  <title>{% block title%}{% endblock %}</title>
  {% endblock %}
</head>

<body>

  <div class="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <p class="flash {{ category }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </div>
</body>

</html>

ProjectFlask/admin/src/web/templates/users/index.html
{% extends "layout.html" %}
{% block title %} Consultas {% endblock %}

{% block head %}
{{super()}}
{% endblock %}

{% block content %}
<h1>Users</h1>

<table class="index-table box">
    <thead>
        <tr>
            <th>#</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}